#!/bin/bash

mkdir build
cd build

cmake ${CMAKE_ARGS} -G Ninja \
    -D CMAKE_INSTALL_PREFIX:FILEPATH=$PREFIX \
    -D CMAKE_BUILD_TYPE:STRING=Release \
    -D Python3_FIND_STRATEGY:STRING=LOCATION \
    -D Python3_FIND_FRAMEWORK:STRING=NEVER \
    -D SWIG_HIDE_WARNINGS:BOOL=ON \
    -D PYTHONOCC_INSTALL_DIRECTORY:FILEPATH=$SP_DIR/OCC \
    -D PYTHONOCC_MESHDS_NUMPY:BOOL=ON \
    -D Python3_NumPy_INCLUDE_DIR=$SP_DIR/numpy/_core/include \
    ..

ninja install
