{% set version = "7.9.0" %}
{% set occt_version = "7.9.0" %}
{% set build = 0 %}

# Higher number -> Always prioritize "all" variant over "novtk" variant
{% set build = build + 100 %}   # [variant == "novtk"]
{% set build = build + 200 %}   # [variant == "all"]

package:
  name: pythonocc-core
  version: {{ version }}

source:
  url: https://github.com/tpaviot/pythonocc-core/archive/{{ version }}.tar.gz
  sha256: 98e53657f54e8a9c3477a81c0b4a11bc6659d5f60123e263419521b42a8e111f

build:
  string: {{ variant }}_h{{ PKG_HASH }}_{{ build }}
  number: {{ build }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - ninja
    - cmake
    - swig 4.3.0
  host:
    - python
    - occt {{ occt_version }} *{{ variant }}*
    - numpy
  run:
    - python
    - occt {{ occt_version }} *{{ variant }}*
    - svgwrite
  run_constrained:
    - occt {{ occt_version }} *{{ variant }}*

test:
  source_files:
    - test
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI
  requires:
    - pyqt >=5
    - pytest
    - mypy

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: python bindings for opencascade (occt)
  description: |
    pythonocc is a python package whose purpose is 
    to provide 3D modeling features. It is intended 
    to CAD/PDM/PLM and BIM related development.
  dev_url: https://github.com/tpaviot/pythonocc-core

extra:
  recipe-maintainers:
    - krande
    - looooo
