{% set version = "7.5.0rc1" %}

package:
  name: pythonocc-core
  version: {{ version }}

source:
  url: https://github.com/tpaviot/pythonocc-core/archive/{{ version }}.tar.gz
  sha256: 6d62002244a0e7f4e5c1ad590d332a60601c44b2501ad017361443b54371e667

build:
  number: 0
  skip: true  # [py < 37]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - ninja
    - cmake
    - swig >=3.0.11
  host:
    - python
    - occt
    - tbb-devel
  run:
    - python
    - occt
    - six

test:
  source_files:
    - test
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI
  requires:
    - pyqt >=5

about:
  home: http://www.pythonocc.org/
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: python bindings for opencascade (occt)
  description: |
    pythonocc is a python package whose purpose is 
    to provide 3D modeling features. It is intended 
    to CAD/PDM/PLM and BIM related development.
  dev_url: https://github.com/tpaviot/pythonocc-core

extra:
  recipe-maintainers:
    - looooo
