{% set version = "7.5.1" %}

package:
  name: pythonocc-core
  version: {{ version }}

source:
  url: https://github.com/tpaviot/pythonocc-core/archive/{{ version }}.tar.gz
  sha256: 52a0e2cd5fc2255ab7c8a91f874148b177b2ce9032f43b3f4844bbc27ccffd38

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - ninja
    - cmake
    - swig
  host:
    - python
    - occt 7.5.1
    - tbb-devel
  run:
    - python
    - occt        # [unix]
    - occt 7.5.1  # [win]
    - six

test:
  source_files:
    - test
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI
  requires:
    - pyqt >=5

about:
  home: http://www.pythonocc.org/
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: python bindings for opencascade (occt)
  description: |
    pythonocc is a python package whose purpose is 
    to provide 3D modeling features. It is intended 
    to CAD/PDM/PLM and BIM related development.
  dev_url: https://github.com/tpaviot/pythonocc-core

extra:
  recipe-maintainers:
    - looooo
