{% set version = "7.8.1" %}
{% set build = 0 %}

# Higher number -> Always prioritize "all" variant over "novtk" variant
{% set build = build + 100 %}   # [variant == "novtk"]
{% set build = build + 200 %}   # [variant == "all"]

package:
  name: pythonocc-core
  version: {{ version }}

source:
  url: https://github.com/tpaviot/pythonocc-core/archive/{{ version }}.tar.gz
  sha256: 098dfa2d13676b98d3cf7b5f686c2369d67327e30fd9279dff10196138766702

build:
  string: {{ variant }}_h{{ PKG_HASH }}_{{ build }}
  number: {{ build }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - ninja
    - cmake
    - swig 4.1.1
  host:
    - python
    - occt {{ version }} *{{ variant }}*
    - numpy
  run:
    - python
    - occt {{ version }} *{{ variant }}*
    - six
    - {{ pin_compatible("numpy") }}
    - svgwrite
  run_constrained:
    - occt {{ version }} *{{ variant }}*

test:
  source_files:
    - test
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI
  requires:
    - pyqt >=5

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: python bindings for opencascade (occt)
  description: |
    pythonocc is a python package whose purpose is 
    to provide 3D modeling features. It is intended 
    to CAD/PDM/PLM and BIM related development.
  dev_url: https://github.com/tpaviot/pythonocc-core

extra:
  recipe-maintainers:
    - looooo
